'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Match = { id:string; matchup:string; match_date:string; match_time:string; court:string; status:string; result?:string|null; cancellation_reason?:string|null };
type Draft = Omit<Match,'id'>;
const teams=[['1','Dipesh, Vipin'],['3','Gaurav, Anish'],['4','Amit, Ananth'],['6','Nissarg, Aniket'],['8','Manikumar, Arindam'],['10','Vibhor, Gourav'],['13','Manoj, Srinivas']];
const label=(id:string)=>{const t=teams.find(x=>x[0]===id);return t?`Team #${t[0]} — ${t[1]}`:`Team #${id}`};
const blank=():Draft=>({matchup:'',match_date:'',match_time:'10:00',court:'Court 2',status:'Scheduled',result:'',cancellation_reason:''});
const api=process.env.NEXT_PUBLIC_SUPABASE_URL?`${process.env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/dashboard_matches`:'';
const headers={'Content-Type':'application/json','apikey':process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'','Authorization':`Bearer ${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||''}`,'Prefer':'return=representation'};
function dateText(d:string){return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date(`${d}T12:00:00`))}
function countdown(d:string,status:string){if(status==='Completed')return 'COMPLETED';const n=new Date(), x=new Date(`${d}T12:00:00`);n.setHours(0,0,0,0); const days=Math.round((x.getTime()-n.getTime())/86400000);return days===0?'TODAY':days===1?'TOMORROW':days>1?`IN ${days} DAYS`:status.toUpperCase()}
function teamIds(m:Match){return teams.filter(([id])=>m.matchup.includes(`Team #${id}`)).map(([id])=>id)}
export default function Page(){
 const [matches,setMatches]=useState<Match[]>([]),[filter,setFilter]=useState('All'),[team,setTeam]=useState(''),[draft,setDraft]=useState<Draft>(blank()),[first,setFirst]=useState('10'),[second,setSecond]=useState('3'),[editing,setEditing]=useState<Match|null>(null),[open,setOpen]=useState(false),[note,setNote]=useState(''),[loading,setLoading]=useState(true);
 const load=async()=>{if(!api){setNote('Missing Supabase public environment settings.');setLoading(false);return}const r=await fetch(`${api}?select=*&order=match_date.asc,match_time.asc`,{headers});if(r.ok)setMatches(await r.json());else setNote('Could not load matches. Please refresh.');setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>matches.filter(m=>(filter==='All'||m.status===filter)&&(!team||teamIds(m).includes(team))),[matches,filter,team]);
 const upcoming=filtered.filter(m=>['Scheduled','Pending'].includes(m.status)&&new Date(`${m.match_date}T23:59:59`)>=new Date()).sort((a,b)=>`${a.match_date}${a.match_time}`.localeCompare(`${b.match_date}${b.match_time}`));
 const completed=filtered.filter(m=>m.status==='Completed').sort((a,b)=>b.match_date.localeCompare(a.match_date)); const cancelled=filtered.filter(m=>m.status==='Cancelled').sort((a,b)=>b.match_date.localeCompare(a.match_date)); const next=upcoming[0];
 function begin(m?:Match){if(m){setEditing(m);setDraft(m);const ids=teamIds(m);setFirst(ids[0]||'10');setSecond(ids[1]||'3')}else{setEditing(null);setDraft(blank());setFirst('10');setSecond('3')}setNote('');setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();const matchup=`${label(first)} vs ${label(second)}`;if(first===second){setNote('You selected the same team for both sides. Choose a different opponent.');return}if(!draft.match_date||!draft.match_time||!draft.court){setNote('Add a date, time, and court before saving.');return}if(draft.status==='Completed'&&!draft.result?.trim()){setNote('Enter a match result before marking this match completed.');return}if(draft.status==='Cancelled'&&!draft.cancellation_reason?.trim()){setNote('Enter a cancellation reason before cancelling this match.');return}const conflict=matches.find(m=>m.id!==editing?.id&&m.match_date===draft.match_date&&m.status!=='Cancelled'&&m.status!=='Completed'&&(teamIds(m).includes(first)||teamIds(m).includes(second)));if(conflict){setNote(`${label(teamIds(conflict)[0])} already has a match on ${dateText(draft.match_date)}. Choose another day.`);return}const body={...draft,matchup};const r=await fetch(editing?`${api}?id=eq.${editing.id}`:api,{method:editing?'PATCH':'POST',headers,body:JSON.stringify(body)});if(!r.ok){setNote('We could not save the match. Please try again.');return}setOpen(false);setNote(editing?'Match updated successfully.':'Match scheduled successfully.');load()}
 return <main><style>{`*{box-sizing:border-box}body{margin:0;background:#f5f6f1;color:#17231d;font-family:Arial,sans-serif}main{max-width:1100px;margin:auto;padding:28px 18px 64px}.top,.hero,.card,.panel,form{background:#fff;border:1px solid #e4e8df;border-radius:18px}.top{display:flex;justify-content:space-between;align-items:center;padding:18px 22px}.brand{font-weight:800;font-size:22px}.muted{color:#66736a;font-size:14px}button,select,input,textarea{font:inherit}button{border:0;border-radius:10px;padding:11px 15px;font-weight:700;cursor:pointer}.primary{background:#147a42;color:#fff}.ghost{background:#edf4ee;color:#17663d}.hero{margin-top:18px;padding:26px;display:grid;grid-template-columns:1fr auto;gap:18px;background:linear-gradient(120deg,#fff,#edf8ef)}.eyebrow{color:#147a42;font-weight:800;font-size:12px;letter-spacing:1px}.teams{font-size:25px;font-weight:800;line-height:1.35;margin:12px 0}.vs{color:#718077;font-size:15px}.badge{align-self:start;background:#147a42;color:#fff;border-radius:999px;padding:12px 15px;font-weight:800;white-space:nowrap}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.filters button.active{background:#17231d;color:#fff}.filters select{border:1px solid #d7ddd4;border-radius:10px;padding:10px;background:#fff}.section{margin-top:28px}.section h2{font-size:18px;margin:0 0 11px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{padding:17px}.cardhead{display:flex;justify-content:space-between;gap:8px;font-size:13px;font-weight:800;color:#536257}.matchup{font-size:17px;font-weight:800;line-height:1.45;margin:14px 0}.status{border-radius:999px;padding:5px 9px;background:#e9f6ed;color:#147a42;font-size:12px}.Completed{background:#e9f2ff;color:#285c9e}.Cancelled{background:#f5e9e9;color:#a13c3c}.Pending{background:#fff3dc;color:#93630d}.empty,.notice{padding:20px;background:#fff;border-radius:14px;color:#66736a}.notice{margin:16px 0;color:#17663d}.modal{position:fixed;inset:0;background:#14201877;display:grid;place-items:center;padding:16px;z-index:3}.modal form{width:min(620px,100%);max-height:90vh;overflow:auto;padding:22px}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:13px}.field{display:grid;gap:6px;font-size:13px;font-weight:700}.field input,.field select,.field textarea{border:1px solid #d7ddd4;border-radius:10px;padding:10px;background:#fff;font-weight:400}.wide{grid-column:1/-1}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}@media(max-width:650px){main{padding:14px}.top{padding:15px}.hero{grid-template-columns:1fr;padding:20px}.teams{font-size:21px}.grid{grid-template-columns:1fr}.formgrid{grid-template-columns:1fr}.wide{grid-column:auto}.top .muted{display:none}}`}</style>
 <header className="top"><div><div className="brand">🎾 Tennis League</div><div className="muted">Your league match dashboard</div></div><button className="primary" onClick={()=>begin()}>Schedule match</button></header>{note&&<div className="notice">{note}</div>}
 {next?<section className="hero"><div><div className="eyebrow">NEXT MATCH</div><div className="teams">{next.matchup.replace(' vs ','\nvs\n').split('\n').map((x,i)=><div className={x==='vs'?'vs':''} key={i}>{x}</div>)}</div><div>{dateText(next.match_date)} · {next.match_time.slice(0,5)} · {next.court}</div><p><span className={`status ${next.status}`}>{next.status}</span></p><button className="ghost" onClick={()=>begin(next)}>Update match</button></div><div className="badge">{countdown(next.match_date,next.status)}</div></section>:<section className="hero"><div><div className="eyebrow">NEXT MATCH</div><div className="teams">No upcoming matches scheduled.</div><div>Schedule the next match to get started.</div></div><button className="primary" onClick={()=>begin()}>Schedule match</button></section>}
 <div className="filters">{['All','Scheduled','Pending','Completed','Cancelled'].map(x=><button key={x} className={filter===x?'active ghost':'ghost'} onClick={()=>setFilter(x)}>{x==='All'?'All matches':x}</button>)}<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All teams</option>{teams.map(([id])=><option key={id} value={id}>{label(id)}</option>)}</select></div>
 <Section title="Upcoming matches" list={upcoming} onEdit={begin} empty={loading?'Loading matches…':'No upcoming matches for this filter.'}/><Section title="Recent results" list={completed} onEdit={begin} empty="No completed matches yet."/><Section title="Cancelled matches" list={cancelled} onEdit={begin} empty="No cancelled matches."/>
 {open&&<div className="modal"><form onSubmit={save}><h2>{editing?'Update match':'Schedule match'}</h2><div className="formgrid"><label className="field">Select first team<select value={first} onChange={e=>setFirst(e.target.value)}>{teams.map(([id])=><option key={id} value={id}>{label(id)}</option>)}</select></label><label className="field">Select opponent<select value={second} onChange={e=>setSecond(e.target.value)}>{teams.map(([id])=><option key={id} value={id}>{label(id)}</option>)}</select></label><label className="field">Date<input type="date" value={draft.match_date} onChange={e=>setDraft({...draft,match_date:e.target.value})}/></label><label className="field">Time<input type="time" value={draft.match_time} onChange={e=>setDraft({...draft,match_time:e.target.value})}/></label><label className="field">Court<input value={draft.court} onChange={e=>setDraft({...draft,court:e.target.value})}/></label><label className="field">Status<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{['Pending','Scheduled','Completed','Cancelled'].map(s=><option key={s}>{s}</option>)}</select></label>{draft.status==='Completed'&&<label className="field wide">Result / score<textarea value={draft.result||''} onChange={e=>setDraft({...draft,result:e.target.value})} placeholder="Team #10 def. Team #3 · 6–4, 6–3"/></label>}{draft.status==='Cancelled'&&<label className="field wide">Cancellation reason<textarea value={draft.cancellation_reason||''} onChange={e=>setDraft({...draft,cancellation_reason:e.target.value})} placeholder="Rain; courts were closed."/></label>}</div><div className="actions"><button type="button" className="ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">{editing?'Save changes':'Schedule match'}</button></div></form></div>}</main>}
function Section({title,list,onEdit,empty}:{title:string;list:Match[];onEdit:(m:Match)=>void;empty:string}){return <section className="section"><h2>{title}</h2>{list.length?<div className="grid">{list.map(m=><article className="card" key={m.id}><div className="cardhead"><span>{dateText(m.match_date)} · {m.match_time.slice(0,5)}</span><span className={`status ${m.status}`}>{m.status==='Scheduled'?countdown(m.match_date,m.status):m.status}</span></div><div className="matchup">{m.matchup}</div><div className="muted">{m.court}</div>{m.result&&<p><b>{m.result}</b></p>}{m.cancellation_reason&&<p className="muted">Reason: {m.cancellation_reason}</p>}<button className="ghost" onClick={()=>onEdit(m)}>Update match</button></article>)}</div>:<div className="empty">{empty}</div>}</section>}